### ISSUE TITLE
1. Introducción

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#1]
Resumen del proyecto, propósito, alcance, objetivos, entregables e hitos principales. Alrededor de una página es suficiente.  

Incluir una breve descripción de la estructura del resto del documento.

**Comment by AlbertoCalvoRubio** [comment]
Pendiente de decidir con el grupo si cualquiera puede subir contenido o solo artistas confirmados

**Comment by AlbertoCalvoRubio** [comment]
Eliminado que cada uno pueda subir sus canciones.
Incluir entregables e hitos de forma resumida. Fijarse en los puntos que especifican eso a lo largo de la memoria o preguntar a los demás.

**Comment by AlbertoCalvoRubio** [comment]
Para la segunda entrega:
- Añadir nuevo planteamiento de hitos semanales y entregas
- Otras modificaciones que resulten del nuevo planteamiento

**Comment by oscarbaselga** [comment]
No ha sido necesario actualizar los hitos y las entregas establecidos en la primera versión, siguen el transcurso del proyecto sin cambios.
