### ISSUE TITLE
4.1 Análisis de requisitos

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#10]
Completar y detallar los requisitos preliminares incluidos en la propuesta técnica y económica. Recordad que los requisitos deben ser completos, concretos, medibles cuando tenga sentido y lo menos ambiguos posible. También es importante que estén identificados para facilitar su trazabilidad.

**Comment by AlbertoCalvoRubio** [comment]
Tras reunión con profesor:
- Añadir identificadores únicos
- Fusionar requisitos de backend y frontend
- Añadir bocetos en los requisitos en vez de las descripciones (Puede haber alguna pequeña descripción para que se entienda mejor)

**Comment by AlbertoCalvoRubio** [comment]
Corregir errores menores indicados en Drive

**Comment by AlbertoCalvoRubio** [comment]
Revisado y terminado

**Comment by AlbertoCalvoRubio** [comment]
Para la entrega final:
- No diferenciar RNF entre los de sistema y los de backend y frontend.
- Asegurarse de que la última versión tiene bien los requisitos con código RF y RNF (También Alberto en latex)

**Comment by Alvarogd6** [comment]
Ahora no se diferencian los RNF entre los de sistema y los de Backend y Frontend y cada requisito tiene un identificador único

**Comment by AlbertoCalvoRubio** [comment]
Revisado
