### ISSUE TITLE
4.2 Diseño del sistema

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#11]
- Diagramas arquitecturales (de módulos, de componentes y conectores, de distribución), patrones de diseño y estilos arquitecturales que se aplicarán. Las interfaces (de módulos y de componentes) son especialmente importantes. También lo son los protocolos de comunicación entre componentes.
- Tecnologías elegidas (lenguajes de programación, componentes que se integrarán, API web externas con las que se conectará etc.).
- Otros aspectos técnicos de interés (p.ej. si hay base de datos si va a ser SQL o NoSQL, si hay una API Web va a ser REST[ful] o no, si algunas de las operaciones van a ser asíncronas o no, si va a ser una aplicación móvil o de escritorio será nativa o se van a usar tecnologías web, cómo se van a considerar los requisitos de seguridad o de prestaciones, cómo y dónde se harán las instalaciones y despliegues etc.)

Hay que justificar todas las decisiones de diseño. Esto exige contestar a dos preguntas sobre cada decisión: ¿qué alternativas se barajaron? y ¿por qué se eligió una y no las otras?

**Comment by ghost** [comment]
Ya he explicado del 4.2 el tema de si vamos a usar tecnologias web o aplicaciones nativas.

**Comment by AlbertoCalvoRubio** [comment]
Tras reunión con profesor:
- Corregir indicación profesor acerca de la seguridad
- Añadir diagramas de módulos, componentes, clases, patrones de diseño
- Justificar cada uno de los apartados ¿Por que se ha hecho así?

**Comment by AlbertoCalvoRubio** [comment]
Reparto específico de algunas tareas:
Diagrama de despliegue renovado indicando como interviene docker y heroku de forma local y cloud: @AlbertoCalvoRubio 
Diagrama de clases, componentes y paquetes: @fntkg @luisgg98 @saul205 cada uno de su correspondiente respositorio.

**Comment by AlbertoCalvoRubio** [comment]
Faltan diagrama de componentes y de paquetes de las tres partes. Corregir alguna indicación hecha en Google Docs.

**Comment by AlbertoCalvoRubio** [comment]
Corregido

**Comment by AlbertoCalvoRubio** [comment]
Para la entrega final
- Diagrama de despliegue: Angular en el navegador del usuario cuando se hace el despliegue final. Cambiar diagrama de despliegue con la aplicación web del cliente está fuera de Heroku.

- Diagrama de clases de cliente distinto para cada frontend
- Añadir el patrón arquitectural Singleton y los patrones que estén incluidos en los frameworks
- Documentar TODOS los diagramas (explicarlos)
- Bibliotecas en los diagramas de paquetes y módulos
- Añadir clases de conexión y modelo de datos de Flask a la base de datos (Domain modeling en Google)
- El diagrama de objetos de la BD en el servidor son las tablas
- Cambiar los diagramas de clases de la BD por el E/R e indicar que se está utilizando un ORM (SQLAlchemy)
- Diagrama de componentes y conectores: profundizar en los clientes indicando ¿qué componentes hacen las peticiones http? Si hay un patrón indicar con un ejemplo (Proxy?). Añadir en Servidor una cajita que ponga modelo de datos (y luego se explica)
- Documentar la API con un link a la wiki de github
- Añadir referencias y descripción a las figuras del documento (Alberto Latex)
- Comentar un poco las interfaces en las imágenes de los prototipos
- Explicar el mapa de navegación de web y android
- Añadir un caso de uso para registro
- Añadir texto o títulos de pantalla (central, registro) o por secciones

**Comment by ghost** [comment]
He añadido el diagrama de clases de web en el apartado **Diagrama de clases**, consta de una imagen y texto

**Comment by AlbertoCalvoRubio** [comment]
Revisado
