### ISSUE TITLE
3.1.1 Procesos de inicio del proyecto

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#3]
- Cómo se van a identificar y asignar recursos (p.ej. conseguir servidores en cloud o teléfonos móviles para pruebas, pero también registrarse para acceder a API que se quieran integrar o a herramientas online que se quieran usar etc.). 
- Cómo se va a abordar la formación inicial de los miembros del equipo (revisar qué tecnologías se van a usar, qué componentes se van a integrar, con qué API hay que conectar y quiénes tienen que formarse, o autoformarse, en todas esas cosas y de qué manera (hacer algún curso online, planificar algo de tiempo para auto-formación con tutoriales y documentación etc.).

**Comment by AlbertoCalvoRubio** [comment]
Falta añadir información acerca de la formación realizada para poder hacer el proyecto

**Comment by AlbertoCalvoRubio** [comment]
Tras reunión con el profesor:
- Quitar los requisitos no funcionales
- Explicar los procesos de inicio: como creación de repositorios, como se consiguen servidores de Heroku, como se forman los nuevos usuarios (ser conciso con que tutoriales se han seguido) respecto a todas las tecnologías que se utilizan en el proyecto y dependiendo de cada grupo, NO las tecnologías sino el COMO me formo para ellas
- Identificar cualquier otro proceso de inicio no identificado aún

**Comment by AlbertoCalvoRubio** [comment]
Tras la reunión con el profesor:
- Como se entra en las herramientas indicadas (Punto de vista de un usuario nuevo), que rol es el encargado de introducirlo en la herramienta/grupo, asignación de permisos
- Como se crean los issues, que criterio hay para crearlos, cerrarlos, reabrirlos, moverlos de un estado a otro, como se asignan
- Google Calendar: como se decide que hitos deben aparecer aqui y como se añaden, hay notificaciones, como se reasignan las fechas
- Como se cuantifica el progreso, evitar subjetividad
- Como se realizan las actas, quien es el encargado de tomar notas

**Comment by AlbertoCalvoRubio** [comment]
El límite de tiempo de los dynos de Heroku en la versión gratuita es de 550h.

**Comment by AlbertoCalvoRubio** [comment]
Correcto, se nota mucho los últimos cambios. Así da gusto

**Comment by AlbertoCalvoRubio** [comment]
Para la entrega final:
- Poner urls repos que hay
- Cambiar 'se decanta' por 'nos decantamos'

**Comment by aFacorroLoscos** [comment]
Anexos puestos y cambio realizado.
