### ISSUE TITLE
3.1.3 Procesos técnicos

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#5]
Describir los métodos, herramientas y técnicas necesarios tanto para construir el software (p.ej. herramientas de desarrollo) como para desplegarlo y probarlo (todos los necesarios para dar soporte a los planes descritos en la sección 3.2).

**Comment by AlbertoCalvoRubio** [comment]
Tras reunión con el profesor:
- Correciones menores indicados en los apuntes del profesor (primeras dos correcciones en rojo)
- Como se instalan las librerias necesarias, no vale suponer "si esta innstalado", pensar en empezar desde cero.
- ¿Que parámetros establecidos? (tercera indicación en rojo)
- No repetir documentación básica de frameworks, si aparece pues que sea muy resumida
- Indicar referencias a Frameworks, librerias, estándares o extensiones instaladas
- Concretar el despliegue en Heroku, que es diferente en nuestro proyecto, cuantos contenedores, como se realiza

**Comment by AlbertoCalvoRubio** [comment]
Las correcciones principales la debe hacer @Greyscarr y puede pedir ayuda a cada uno de los demás miembros asignados.

**Comment by AlbertoCalvoRubio** [comment]
Aplicar correcciones indicadas en Doc de Google

**Comment by AlbertoCalvoRubio** [comment]
Sigue sin estar las correcciones en los procesos de prueba

**Comment by AlbertoCalvoRubio** [comment]
Para esta entrega correcto, habrá que pulirlo para la entrega final

**Comment by AlbertoCalvoRubio** [comment]
Para la entrega final:
- Quitar versiones concretas pero sí nombrar algunas bibliotecas (las más importantes) y en qué ficheros se encuentran anotadas (Backend: requirements.txt, Android… Web...)
- README.md Explicar procesos de instalación en el README.md y desde la memoria explicar primero un poco todo y que hay más detalle en el fichero readme.md por posibles cambios

**Comment by aFacorroLoscos** [comment]
Versiones quitadas de front-end android, los ficheros ya estaban definidos, así que los he puesto en negrita. Faltaría redactar el README

**Comment by aFacorroLoscos** [comment]
README hecho y cambios realizados en la memoria

**Comment by aFacorroLoscos** [comment]
El punto se explica de la siguiente manera:
1ª Punto: En que rama se trabaja
2ª Punto: Readme, explicando que es y porque de su existencia
3ª Punto: Frontend-Web(Ficheros y librerías)
4ª Punto: Frontend-Movil(Ficheros y librerías)
5ª Punto: Backend(Ficheros y librerías)

**Comment by AlbertoCalvoRubio** [comment]
Revisado
