### ISSUE TITLE
3.2.3 Plan de aseguramiento de la calidad

### ISSUE THREAD

**Issue by AlbertoCalvoRubio** [UNIZAR-30226-2020-10/documentacion#8]
- Guías para la documentación de diseño del software y otros documentos del proyecto, guías para el diseño gráfico de las GUI (estética, usabilidad...).
- Actividades de control de calidad del código que se realizarán: revisiones de código por pares, revisiones de requisitos o diagramas UML por pares, tipos de tests automáticos o manuales que se llevarán a cabo.

**Comment by AlbertoCalvoRubio** [comment]
Añadir los enlaces como pie de página. (Insertar -> Nota a pie de página)
Añade de forma redactada que en el backend además se va a utilizar SQLAlchemy para la creación, mapeo y gestión de la base de datos. (Evita el lenguaje SQL y se hace todo en python)

**Comment by AlbertoCalvoRubio** [comment]
Tras reunión con profesor:
- Añadir imagenes, plantillas, figuras
- Elegir fuente (Que Sans)
- Donde se definen los colores
- Quitar último apartado indicado en el pdf de corrección
- Cuando se hacen las pruebas manuales
- Como medir la calidad del código y como (Lo revisa alguien, algún analizador estático...)
- Calidad de la documentación

**Comment by Alvarogd6** [comment]
Falta poner analizador estático y estético en el backend y estético en Android

**Comment by AlbertoCalvoRubio** [comment]
Totalmente increíble el trabajo y la redacción. Solo queda añadir alguna referencia al proceso de test cuando se haya creado.

**Comment by AlbertoCalvoRubio** [comment]
Para la entrega final:
- Indicar objetivos de los test (Backend pj toda la API), pensar si poner porcentajes (Backend 100% no? por peticiones de test a toda la API) u otras medidas

**Comment by Alvarogd6** [comment]
He añadido lo siguiente:
La función de dichos tests es para comprobar el correcto funcionamiento de las peticiones de la API y de si las entidades y sus relaciones en la base de datos son correctas y se pueden añadir/eliminar/borrar elementos. En el caso del Frontend, los tests se realizan para comprobar si los diferentes componentes/clases/pantallas funcionan como se espera (como el control del reproductor o el cerrar sesión del usuario).

y se ha cambiado la tipografía de Moderne Sans a Roboto Mono (cambiando el link de la referencia 10)

**Comment by AlbertoCalvoRubio** [comment]
Revisado
